replicas: 1

image:
  repository: conorfennell/paint-batch-optimizer
  tag: 1.0.0
  pullPolicy: Always

resources:
  requests:
    cpu: 100m
    memory: 100Mi

autoscaler:
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 40