replicas: 1

image:
  repository: conorfennell/paint-batch-optimizer
  tag: 1.1.0
  pullPolicy: Always

resources:
  requests:
    memory: 160Mi
  limits:
    memory: 160Mi

autoscaler:
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 60

service:
  dns: api.paintbatch.com

env:
  HOST: "0.0.0.0"
  PORT: "8080"
  MAX_CUSTOMERS: "2000"
  MAX_PAINTS: "2000"
  MAX_CUSTOMER_CHOICES: "3000"
