language: scala
scala:
- 2.12.7
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
script:
- sbt test
deploy:
- provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && echo 'version in ThisBuild := "$TRAVIS_TAG"' > version.sbt && sbt docker:publish
  on:
    branch: master
    tags: true