---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "example-app.fullname" . }}
  labels:
    chart: {{ template "example-app.chart" . }}
    app: {{ template "example-app.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ template "example-app.name" . }}
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: {{ template "example-app.name" . }}
        release: "{{ .Release.Name }}"
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy}}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        {{- if .Values.env }}
        env:
        {{- range $key, $value := .Values.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /_internal_/healthcheck
            port: http
        readinessProbe:
          httpGet:
            path: /_internal_/healthcheck
            port: http
        {{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        {{- end }}