apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: paint-batch-optimizer
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: paint-batch-optimizer
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 40