---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "example-app.fullname" . }}
  labels:
    chart: {{ template "example-app.chart" . }}
    app: {{ template "example-app.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:    
    app: {{ template "example-app.name" . }}
  type: LoadBalancer
  ports:  
  - name: http
    port: 80
    targetPort: http
    protocol: TCP