---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "example-app.fullname" . }}
  labels:
    chart: {{ template "example-app.chart" . }}
    app: {{ template "example-app.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: {{ template "example-app.fullname" . }}
      host: paintbatch.com
      prefix: /
      service: {{ template "example-app.fullname" . }}
spec:
  selector:    
    app: {{ template "example-app.name" . }}
  type: ClusterIP
  ports:  
  - name: http
    port: 80
    targetPort: http
    protocol: TCP