---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "example-app.fullname" . }}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: {{ template "example-app.fullname" . }}
      host: {{ .Values.service.dns }}
      prefix: /
      service: "{{ template "example-app.fullname" . }}.{{ .Release.Namespace }}"
  labels:
    chart: {{ template "example-app.chart" . }}
    app: {{ template "example-app.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:    
    app: {{ template "example-app.name" . }}
  type: LoadBalancer
  ports:  
  - name: http
    port: 80
    targetPort: http
    protocol: TCP